#!/bin/bash
# =====================================
#           配列操作関数定義
# =====================================

# ----------------
#     関数定義
# ----------------
arr.indexOf() {
  # 指定された要素が配列のどこにあるかを返します
  # param1 指定要素
  # param2+ 配列要素
  # return 配列インデックス
  # returnCd 0:配列に存在した 1:配列に存在しなかった
  if [[ "$#" -eq 0 ]];then
    echo -1
    return 1
  fi
  readonly local target="$1";shift
  readonly local elements=( "$@" )
  local i
  for i in "${!elements[@]}";do
    if [[ "${elements[i]}" == "${target}" ]];then
      echo "$i"
      return 0
    fi
  done
  echo -1
  return 1
}

arr.hasElement() {
  # 指定された要素が配列に含まれるかを返します
  # param1 指定要素
  # param2+ 配列要素
  # returnCd 0:含まれる 1:含まれない
  readonly local target="$1";shift
  readonly local elements=( "$@" )
  local i
  for e in "${elements[@]}";do
    if [[ "${e}" == "${target}" ]];then
      return 0
    fi
  done
  return 1
}
alias arr.contains='arr.hasElement'

arr.car() {
  # 配列の先頭を返します
  # param1+ 配列要素
  # return 配列の先頭要素
  echo "$1"
}

arr.cdr() {
  # 配列の先頭以降を返します
  # param1+ 配列要素
  # return 配列の先頭以降の要素
  shift
  echo "$@"
}

arr.last() {
  # 配列の最後の要素を返します
  # param1+ 配列要素
  # return 配列の最後の要素
  readonly local args=( "$@" )
  readonly local size=${#args[@]}
  if [[ "$size" -gt 0 ]];then
    echo "${args[$size-1]}"
  fi
}
