#!/bin/bash
# =====================================
#           ファイル操作関数定義
# =====================================
base="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"

# ----------------
#     関数定義
# ----------------
file.executable() {
  # 指定されたファイルが実行可能かを返します
  # param1 ファイルパス
  # returnCd 0:実行可能 1:実行不可
  [[ "$#" -ne 0 ]] && [[ ! -z "${1+x}" ]] && [[ -x "${1}" ]]
}

file.writable() {
  # 指定されたファイルが書込可能かを返します
  # param1 ファイルパス
  # returnCd 0:書込可能 1:書込不可
  [[ "$#" -ne 0 ]] && [[ ! -z "${1+x}" ]] && [[ -w "${1}" ]]
}

file.readable() {
  # 指定されたファイルが読込可能かを返します
  # param1 ファイルパス
  # returnCd 0:読込可能 1:読込不可
  [[ "$#" -ne 0 ]] && [[ ! -z "${1+x}" ]] && [[ -r "${1}" ]]
}

file.size() {
  # 指定されたファイルのバイトサイズを返します
  # 指定がない場合はカレントディレクトリのサイズ一覧が表示されます
  # opt: h サイズをKやMなどの分かりやすい単位にまとめます
  # param1+ ファイルパス
  # return ファイルサイズ
  local OPTIND
  local option=-l
  while getopts h OPT
  do
    case $OPT in
      h) option=-lh
      ;;
    esac
  done
  shift $((OPTIND - 1))

  ls ${option} "$@" | awk '/^-/{print $5"\t"$NF}'
}
