#!/bin/bash
# =====================================
#           ログ出力関数定義
# =====================================

# ----------------
#     初期設定
# ----------------
# ※ 上書きしたい場合は、このファイルを読み込んだ後で実施してください
# ログディレクトリ
LOG_DIR=
# ログファイル
LOG_FILE='%file_%timestamp.log'
# タイムスタンプフォーマット（date 関数で使用可能なフォーマット）
TIMESTAMP_FORMAT='%Y%m%d'
# ログフォーマット
# 利用可能変数
#   %datetime : TIMESTAMP_FORMAT による日付で置換される
#   %level : ログレベルで置換される
#   %file : 対象ファイルで置換される
#   %func : 対象の関数名で置換される
#   %line : 行番号で置換される
#   %msg : メッセージが置換される
#   %eol : LINE_SEPARATOR による改行コードで置換される
LOG_FORMAT='[%datetime][%level][%file#%func:%line]:%msg%eol'
# 日時フォーマット（date 関数で使用可能なフォーマット）
DATETIME_FORMAT='%Y-%m-%d %H:%M:%S'
# 改行コード
LINE_SEPARATOR='\n'

# ----------------
#     関数定義
# ----------------
log.settings() {
  # 現在の設定値を表示します
  echo "LOG_DIR=$LOG_DIR"
  echo "LOG_FILE=$LOG_FILE"
  echo "TIMESTAMP_FORMAT=$TIMESTAMP_FORMAT"
  echo "LOG_FORMAT=$LOG_FORMAT"
  echo "DATETIME_FORMAT=$DATETIME_FORMAT"
  echo "LINE_SEPARATOR=$LINE_SEPARATOR"
}

log.setAbort() {
  # 異常終了時のエラー表示設定
  # param1 エラー表示フラグ(on | off)
  #--
  # usage) log.setAbort [on|off]
  local flg='ON'
  if [ "$#" -gt 0 ];then
    flg=$(echo ${1:-"ON"} | awk '{print toupper($0)}')
  fi
  if [ "_$flg" == "_ON" ];then
    echo "abort notice : on"
    trap 'log.abort; exit 1' HUP INT QUIT TERM
  else
    trap - HUP
    trap - INT
    trap - QUIT
    trap - TERM
    echo "abort notice : off"
  fi
}

log.abort() {
  # 異常終了時のログ出力
  log.logger 'FATAL' '=================' 1>&2
  log.logger 'FATAL' '==== ABORTED ====' 1>&2
  log.logger 'FATAL' '=================' 1>&2
  log.logger 'FATAL' "An error occurred Exiting..." 1>&2
}

log.setTrace() {
  # トレースログ設定
  # 必要なシェルなどで有効にするとコマンドレベルで実行状況を出力します
  # trapを使用しているため、関数スコープで動作します
  # ※ 通常はこれを使用するよりも 'bash -x command' を使用した方が効果的です
  # param1 トレースフラグ(on | off)
  #--
  # usage) log.setTrace [on|off]
  local flg='ON'
  if [ "$#" -gt 0 ];then
    flg=$(echo ${1:-"ON"} | awk '{print toupper($0)}')
  fi
  if [ "_$flg" == "_ON" ];then
    echo "trace : on"
    trap 'log.logger "TRACE" "--exec-> ${BASH_COMMAND[@]//\"/}"' DEBUG
  else
    trap - DEBUG
    echo "trace : off"
  fi
}

log.logger() {
  # ロガー
  # ログテンプレート内のプレイスホルダー"{}"を置換パラメータに置き換えます
  # param1 ログレベル
  # param2 ログテンプレート
  # param3+ 置換パラメータ
  # returnCd 0:正常 9:パラメータエラー
  #--
  # usage) log.logger '[INFO|WARN|ERROR]' '{} is {}.' 'This' 'mine'
  if [ "$#" -lt 1 ];then
    errorLog "Illegal palameters exception: You should give log-level and message or more parameters."
    return 9
  fi
  local level="$1";shift
  local message
  if [ "$#" -eq 0 ];then
    message=''
  else
    message=$(echo "$1" | sed -e 's|/|\\/|g');shift
  fi
  local params=( "$@" )

  local logformat="${LOG_FORMAT}"
  local linesepalator="${LINE_SEPARATOR}"
  local datetime=$(date +"${DATETIME_FORMAT}")
  local file=$(basename "${BASH_SOURCE[2]}" | sed -e 's|/|\\/|g')
  local line="${BASH_LINENO[1]}"
  local func="${FUNCNAME[2]}"
  if [ "$level" == "TRACE" ] || [ "$level" == "FATAL" ];then
    # トレースログ、フェイタルログの場合は取得階層が1つ上になる
    file=$(basename "${BASH_SOURCE[1]}" | sed -e 's|/|\\/|g')
    line="${BASH_LINENO[0]}"
    func="${FUNCNAME[1]}"
  fi

  local msg="$message"
  local p
  for p in "${params[@]}"; do
    p=$(echo "$p" | sed -e 's|/|\\/|g')
    msg=$(echo "$msg" | sed -e "s/{}/$p/")
  done

  # ログ出力
  local spaces='     '
  echo -ne "$logformat" | \
    sed -e "s/%datetime/$datetime/g" \
        -e "s/%level/$level${spaces:${#level}}/g" \
        -e "s/%file/$file/g" \
        -e "s/%func/$func/g" \
        -e "s/%line/$line/g" \
        -e "s/%msg/$msg/g" \
        -e "s/%eol/${linesepalator}/g"
}

log.info() {
  # INFOログ
  # param1 ログテンプレート
  # param2+ 置換パラメータ
  log.logger 'INFO' "$@"
}

log.warn() {
  # WARNログ
  # param1 ログテンプレート
  # param2+ 置換パラメータ
  log.logger 'WARN' "$@" 1>&2
}

log.error() {
  # ERRORログ
  # param1 ログテンプレート
  # param2+ 置換パラメータ
  log.logger 'ERROR' "$@" 1>&2
}

log.to() {
  # 対象処理を実施してログをファイルに出力します
  # input-stream 入力ストリーム
  # param1 ログファイル名（なければデフォルト値）
  # param2+ 対象処理（入力ストリーム優先）
  local timestamp=$(date +"${TIMESTAMP_FORMAT}")
  local basefile=$(echo "$0" | sed -e 's/^-*//')
  local logfile=$(echo "$LOG_FILE" | sed -e "s/%timestamp/$timestamp/g" -e "s/%file/$(basename ${basefile%.*})/g")
  if [ "$#" -gt 0 ];then
    if [ $(echo "$1" | grep -c '/') -eq 0 ];then
      logfile="${LOG_DIR:-$(dirname $0))}/${1}";shift
    else
      logfile="${1}";shift
    fi
  fi
  local cmd
  if [ "$#" -gt 0 ];then
    cmd="$1";shift
  fi
  local args=( "$@" )
  dir="$(dirname $logfile)"
  if [ ! -d "$dir" ];then
    echo "'$dir' is not found."
    mkdir -p "$dir"
    echo "'$dir' is ceated."
  fi
  if [ -t 0 ]; then
    if [ "${cmd:+_}" == "_" ];then
      "$cmd" "${args[@]}" 2>&1 | tee -a "$logfile"
    fi
  else
    cat - | tee -a "$logfile"
  fi
}
