#!/bin/bash
# =====================================
#             定義表示関数定義
# =====================================
base="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"

# ----------------
#     関数定義
# ----------------
ref() {
  # 指定された関数が既に読みこまれている場合に、その定義を表示します
  # このディレクトリに定義された関数以外は type コマンドの結果を返します
  # param1 関数名
  if [[ "$#" -eq 0 ]];then
    echo "usage: ref <funcname>" 1>&2
    return 1
  fi
  if [[ $(cat "${BASH_SOURCE:-$0}" | grep -e "^${1}.*(" | wc -l) -ne 0 ]];then
    cat "${BASH_SOURCE:-$0}" | sed -n -e "/^${1}.*{/,/^}/p"
  elif [[ -f "$base/${1}" ]];then
    cat "$base/${1}"
  else
    if [[ "$(type -t $1)" == "function" ]] && [[ -f "$base/${1%.*}" ]];then
      cat "$base/${1%.*}" | sed -n -e "/^${1}.*{/,/^}/p"
    else
      type "$1"
    fi
  fi
}

[[ "$#" -ne 0 ]] && ref "$1"
