#!/bin/bash
# =====================================
#            文字列関数定義
# =====================================

# ----------------
#     関数定義
# ----------------
str.indexOf() {
  # 検索対象文字列が入力文字列（もしくはストリーミング）の何文字目にあたるかを返します
  # input-stream 入力ストリーム
  # param1 検索対象文字列
  # param2 入力文字列
  # return 検索対象文字列が何文字目にあたるか
  # returnCd 0:文字列が見つかった 1:文字列が見つからなかった
  local idx
  if [ -t 0 ]; then
    local target=''
    if [ "$#" -gt 0 ];then
      target="${1}";shift
    fi
    local line=''
    if [ "$#" -gt 0 ];then
      line="${1}"
    fi
    idx=$(awk 'BEGIN{ print index("'"${line}"'", "'"${target}"'")-1}')
  else
    local target=''
    if [ "$#" -gt 0 ];then
      target="${1}";shift
    fi
    idx=$(cat - | awk '{ print index($0, "'"${target}"'")-1}')
  fi
  echo "$idx"
  [[ ! "$idx" == "-1" ]]
}

str.contains() {
  # 検索対象文字列が入力文字列（もしくはストリーミング）に含まれるかを返します
  # input-stream 入力ストリーム
  # param1 検索対象文字列
  # param2 入力文字列
  # returnCd 0:文字列が含まれている 1:文字列が含まれていない
  local index
  if [ -t 0 ]; then
    local target=''
    if [ "$#" -gt 0 ];then
      target="${1}";shift
    fi
    local line=''
    if [ "$#" -gt 0 ];then
      line="${1}"
    fi
    index=$(awk 'BEGIN{ print index("'"${line}"'", "'"${target}"'")}')
  else
    local target=''
    if [ "$#" -gt 0 ];then
      target="${1}";shift
    fi
    index=$(cat - | awk '{ print index($0, "'"${target}"'")}')
  fi
  [[ ! "$index" == "0" ]]
}

str.match() {
  # パターンが入力文字列にマッチするかを判定し、判定結果を返します
  # param1 パターン
  # param2 入力文字列
  # return マッチした文字列を格納した配列
  # returnCd 0:文字列が含まれている 1:文字列が含まれていない
  if [[ "$#" -ge 2 ]];then
    local regex="$1";shift
    local line="$1"
    if [[ "$line" =~ $regex ]];then
      echo "${BASH_REMATCH[@]}"
      return 0
    fi
  fi
  return 1
}

str.toLower() {
  # 入力文字列を小文字に変換します
  # param1+ 文字列
  # return 小文字に変換した文字列
  # if [ -t 0 ]; then
  #   [[ "$#" -ne 0 ]] &&  echo "$@" | tr '[:upper:]' '[:lower:]'
  # else
  #   cat - | tr '[:upper:]' '[:lower:]'
  # fi
  if [ -t 0 ]; then
    [[ "$#" -ne 0 ]] &&  echo "$@"
  else
    cat -
  fi | tr '[:upper:]' '[:lower:]'
}

str.toUpper() {
  # 入力文字列を大文字に変換します
  # param1+ 文字列
  # return 大文字に変換した文字列
  if [ -t 0 ]; then
    [[ "$#" -ne 0 ]] &&  echo "$@"
  else
    cat -
  fi | tr '[:lower:]' '[:upper:]'
}

str.toLf() {
  # 改行コードを CRLF -> LF 変換します
  # param1+ ファイル名
  # return 改行コードを LF に変換した文字列
  if [ -t 0 ]; then
    [[ "$#" -ne 0 ]] &&  cat "$@"
  else
    cat -
  fi | tr -d \\r
}

str.toCrLf() {
  # 改行コードを LF -> CRLF 変換します
  # param1+ ファイル名
  # return 改行コードを LF に変換した文字列
  if [ -t 0 ]; then
    [[ "$#" -ne 0 ]] &&  cat "$@"
  else
    cat -
  fi | str.toLf | sed 's/$/\r/g'
}

str.isInteger() {
  # 入力文字列が整数かどうかを返します
  # param1 入力文字列
  # returnCd 0:整数 1:整数ではない
  [[ "$#" -eq 0 ]] && return 1
  expr "${1}" + 1 >/dev/null 2>&1
  [[ $? -lt 2 ]]
}

str.isNumber() {
  # 小数の場合も考慮し、入力文字列が数値かどうかを返します
  # param1 入力文字列
  # returnCd 0:数値 1:数値ではない
  [[ "$#" -eq 0 ]] && return 1
  str.isInteger "${1/./}"
  return "$?"
}

str.times() {
  # 文字列を指定回数繰り返します
  # param1 文字列
  # param2 指定回数（デフォルト1回）
  # return 指定回数繰り返された文字列
  eval "printf '${1:-''}%.0s' {1..${2:-1}}"
}
