#!/bin/bash
# =====================================
#        サブプロンプト関数定義
# =====================================
base="$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)"

# ----------------
#     関数定義
# ----------------
sub.new() {
  # サブプロンプトを開始します
  (
    unset tmpfile
    trap '[[ "${tmpfile}" ]] && rm -f ${tmpfile}' EXIT HUP INT QUIT TERM RETURN
    local tmpfile=$(mktemp 2>/dev/null||mktemp -t tmp)
    cat >${tmpfile} <<<'''#!/bin/bash --init-file
      PS1="\[\033[01;34m\]\u\[\033[00m\]\$ "
    '''
    bash --init-file ${tmpfile}
  )
}
