#!/bin/bash
# =====================================
#         YAMLファイル変換関数定義
# =====================================

# ----------------
#     関数定義
# ----------------
yml.toEnv() {
  # YAMLを環境変数として使用できる形に変換します
  # 環境変数のキーにドットやハイフンは使用できないため
  # それらが使用されていた場合アンダースコアに変更されます
  # input-stream 入力ストリーム
  # param1 入力ファイル
  # param2 追加接頭語
  # return 環境変数で使用できるようにしたYAML内容
  # returnCd 0:変換できた 1:変換できなかった
  local prefix="$1"
  [ -t 0 ] && prefix="$2"
  local s='[[:space:]]*'
  local c='[[:space:]]\+#.*'
  local w='[a-zA-Z0-9_]*[a-zA-Z0-9_\.-]*'
  local l='[-]'
  local illegal='[\.-]'
  local sep='_'
  local fs=$(echo @|tr @ '\034')
  if [ -t 0 ]; then
    [[ "$#" -ne 0 ]] && cat "$1"
  else
    cat -
  fi | \
  sed -ne "s|^\($s\):|\1|" \
       -e "s|^\($s\)\($l$s$w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($l$s$w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($l\)$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($l\)$s[\"']\(.*\)[\"']$c\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($l\)$s\(.*\)$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($l\)$s\(\([^[:space:]][^#]\)\+\)$c\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s#$s\(.*\)\$|\1$fs\2$fs|p" \
       -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$c\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s\(\([^[:space:]][^#]\)\+\)$c\$|\1$fs\2$fs\3|p" \
       -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p" | \
  awk -F$fs '{
    indent = length($1);
    if ($2 !~ /^[-]/) {
      # type: hash
      offset = 0;
      idx = idxs[indent + offset];
      if (length(idx) == 0) {idx=0}
      for (i in idxs) {if (i > indent + offset) {delete idxs[i]}}
      for (i in vname) {if (i > indent + offset) {delete vname[i]}}

      gsub( /'$illegal'/, "_", $2 );
      vname[indent + offset] = $2;
    } else if (length($2) == 1) {
      # type: list
      offset = 1;
      idx = idxs[indent + offset];
      if (length(idx) == 0) {idx=0}
      for (i in idxs) {if (i > indent + offset) {delete idxs[i]}}
      for (i in vname) {if (i > indent + offset) {delete vname[i]}}

      vname[indent + offset] = ("'$fs'")(idx);
      $2 = ("[")(idx)("]");
      idxs[indent + offset] = ++idx;
    } else {
      # type: list + hash
      list_offset = 1;
      idx = idxs[indent + list_offset];
      if (length(idx) == 0) {idx=0}
      offset = match(substr($2, 2, length($2) - 1), /[^[:space:]]/);
      for (i in idxs) {if (i > indent + offset) {delete idxs[i]}}
      for (i in vname) {if (i > indent + offset) {delete vname[i]}}

      lstr = substr($2, offset + 1, length($2) - offset)
      gsub( /'$illegal'/, "_", lstr);
      vname[indent + list_offset] = ("'$fs'")(idx);
      vname[indent + offset] = lstr;
      $2 = ("[")(idx)("]'$sep'")(lstr);
      idxs[indent + list_offset] = ++idx;
      idxs[indent + offset] = 0;
      offset = 0;
    }
    if (length($3) > 0) {
      vn="";
      for (i=0; i<indent + offset; i++) {
        if (length(vname[i]) > 0) {vn = (vn)(vname[i])("'$sep'")}
      }
      gsub( /_'$fs'[0-9]+/, "[&]", vn );
      gsub( /_'$fs'/, "", vn );
      if (idx > 0) {vn = substr(vn, 1, length(vn)-1)}
      printf("%s%s%s=\"%s\"\n", "'$prefix'", vn, $2, $3);
    }
  }'
}
