#!/bin/bash
# =====================================
#           配列操作関数定義
# =====================================

# ----------------
#     関数定義
# ----------------
arr.indexOf() {
  # 指定された要素が配列のどこにあるかを返します
  # param1 指定要素
  # param2+ 配列要素
  # return 配列インデックス
  # returnCd 0:配列に存在した 1:配列に存在しなかった
  if [[ "$#" -eq 0 ]];then
    echo -1
    return 1
  fi
  local target="$1";shift
  local elements=( "$@" )
  local i
  for i in "${!elements[@]}";do
    if [[ "${elements[i]}" == "${target}" ]];then
      echo "$i"
      return 0
    fi
  done
  echo -1
  return 1
}

arr.hasElement() {
  # 指定された要素が配列に含まれるかを返します
  # param1 指定要素
  # param2+ 配列要素
  # returnCd 0:含まれる 1:含まれない
  local target="$1";shift
  local elements=( "$@" )
  local i
  for e in "${elements[@]}";do
    if [[ "${e}" == "${target}" ]];then
      return 0
    fi
  done
  return 1
}
alias arr.contains='arr.hasElement'

arr.car() {
  # 配列の先頭を返します
  # param1+ 配列要素
  # return 配列の先頭要素
  echo "$1"
}
alias arr.head='arr.car'

arr.cdr() {
  # 配列の先頭以降を返します
  # param1+ 配列要素
  # return 配列の先頭以降の要素
  shift
  echo "$@"
}
alias arr.head='arr.tail'

arr.last() {
  # 配列の最後の要素を返します
  # param1+ 配列要素
  # return 配列の最後の要素
  local args=( "$@" )
  local size=${#args[@]}
  if [[ "$size" -gt 0 ]];then
    echo "${args[$size-1]}"
  fi
}

arr.take() {
  # 配列から指定された要素数だけ返します
  # 指定数よりも要素が少ない場合は、あるだけを返します
  # param1 指定要素数
  # param2+ 配列要素
  # return 指定された数分の要素
  # returnCd 0:正常 1:指定要素数が不正
  local limit="$1";shift
  expr "${limit}" + 1 >/dev/null 2>&1
  if [ $? -ge 2 ]; then
    return 1
  fi
  local args=( "$@" )
  local size=${#args[@]}
  if [[ "$size" -lt "$limit" ]];then
    echo "${args[@]}"
  else
    echo "${args[@]:0:$limit}"
  fi
}

arr.drop() {
  # 配列から指定された要素数だけ除外して返します
  # 指定数よりも要素が少ない場合は、空を返します
  # param1 指定要素数
  # param2+ 配列要素
  # return 指定された数分除外した要素
  # returnCd 0:正常 1:指定要素数が不正
  local size="$1";shift
  expr "${size}" + 1 >/dev/null 2>&1
  if [ $? -ge 2 ]; then
    return 1
  fi
  local args=( "$@" )
  local limit=${#args[@]}
  if [[ "$size" -lt "$limit" ]];then
    echo "${args[@]:$size:$limit-1}"
  fi
}
